[package]
name = "cribbage_library"
version = "0.1.0"
edition = "2018"

[dependencies]
arrayvec="0.7.1"
rand= "0.8.4"
serde = { version = "1.0.130", features = ["derive"] }
serde_json= "1.0.67"
strum = "0.22"
strum_macros = "0.22"


