template: external-service
values:
    fqdn: cribbage.cloud
    image: azurecr.io/timfpark/cribbage-api:20211012T232706Z
    app: cribbage-api
    cpu: 0.5 
    memory: 64M
    replicas: 2
    port: 8080
