template: external-service
values:
    publicFQDN: cribbage.cloud
    image: azurecr.io/timfpark/cribbage-api:latest
    app: cribbage-api
    cpu: 0.5 
    memory: 64M
    replicas: 2
    env:
        CRIBBAGE_PORT: 80
