template: external-service
values:
    fqdn: cribbage.cloud
    image: tpark.azurecr.io/cribbage-api:20211029T000956Z
    app: cribbage-api
    cpu: 0.5 
    memory: 64M
    replicas: 2
    port: 8080
