[package]
name = "cribbage-api"
version = "0.1.0"
edition = "2018"

[dependencies]
arrayvec="0.7.1"
serde = { version = "1.0.130", features = ["derive"] }
serde_json= "1.0.67"
actix-web = "3"
actix-rt = "2.2.0"
