on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
name: cribbage-api

env:
    CARGO_TERM_COLOR: always
    DOCKER_BUILDKIT: 1

jobs:
    test-build-push:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout repository"
              uses: actions/checkout@v2

            - name: "Cache cargo dependencies"
              uses: actions/cache@v2
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Run tests
              run: cargo test --verbose

            - name: "Login via Azure CLI"
              uses: azure/login@v1
              with:
                  creds: ${{ secrets.AZURE_CREDENTIALS }}

            - name: "Build and Push Image"
              uses: azure/docker-login@v1
              with:
                  login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}
            - run: |
                  export TAG=`date -u +"%Y%m%dT%H%M%SZ"`
                  docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/cribbage-api:$TAG
                  docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/cribbage-api:$TAG
